/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT4_FTM2CH0SRC_FTM 0x00u /*!<@brief FTM2 channel 0 input capture source select: FTM2_CH0 signal */

/*! @name PORTA2 (number 36), J9[6]/TRACE_SWO
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_TRACE_SWO_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_TRACE_SWO_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_TRACE_SWO_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PORTA12 (number 42), J1[12]/FTM1_CH0/FTM1_QD_PHA
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_FTM1_QD_PHA_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_FTM1_QD_PHA_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_FTM1_QD_PHA_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTA13 (number 43), J1[3]/FTM1_CH1/FTM1_QD_PHB
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_FTM1_QD_PHB_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_FTM1_QD_PHB_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_FTM1_QD_PHB_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTB18 (number 64), J3[3]/FTM2_CH0
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_FTM2_CH0_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_FTM2_CH0_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_FTM2_CH0_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PORTA18 (number 50), X501[1]/EXTAL0
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_Stop_Input_from_ECU_Main_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_Stop_Input_from_ECU_Main_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_Stop_Input_from_ECU_Main_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_Stop_Input_from_ECU_Main_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_Stop_Input_from_ECU_Main_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                                 /* @} */

/*! @name PORTA0 (number 34), J9[4]/SWD_CLK_KV3x
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_SWD_CLK_KV3x_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_SWD_CLK_KV3x_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_SWD_CLK_KV3x_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTA3 (number 37), J9[2]/SWD_DIO_TGTMCU
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_SWD_DIO_TGTMCU_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_SWD_DIO_TGTMCU_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_SWD_DIO_TGTMCU_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTB23 (number 69), NC
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_System_Ready_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_System_Ready_GPIO_PIN_MASK (1U << 23U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_System_Ready_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_System_Ready_PIN 23U                   /*!<@brief PORT pin number */
#define BOARD_System_Ready_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTB21 (number 67), J4[9]/CMP1_OUT
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_BUSY_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_BUSY_GPIO_PIN_MASK (1U << 21U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_BUSY_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_BUSY_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_BUSY_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTC6 (number 78), J1[16]/LLWU_P10/CMP0_IN0
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_CONVSTAB_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_CONVSTAB_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_CONVSTAB_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_CONVSTAB_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_CONVSTAB_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name PORTD4 (number 97), J3[7]/FTM0_CH4
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_FTM0_CH4_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_FTM0_CH4_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_FTM0_CH4_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name DAC0_OUT (number 27), J4[11]/DAC0_OUT
  @{ */
/* @} */

/*! @name PORTC8 (number 80), J4[2]/ADC1_SE4b/CMP0_IN2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_MOTOR_STOP_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_MOTOR_STOP_GPIO_PIN_MASK (1U << 8U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_MOTOR_STOP_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_MOTOR_STOP_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_MOTOR_STOP_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                  /* @} */

/*! @name PORTC4 (number 76), J3[9]/FTM0_CH3
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_FTM0_CH3_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_FTM0_CH3_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_FTM0_CH3_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name DAC1_OUT (number 28), J2[11]/ADC1_SE23
  @{ */
/* @} */

/*! @name PORTC13 (number 85), J1[10]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_Gate_Driver_Pins_Fault_6_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define BOARD_Gate_Driver_Pins_Fault_6_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_Gate_Driver_Pins_Fault_6_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_Gate_Driver_Pins_Fault_6_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_Gate_Driver_Pins_Fault_6_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                                 /* @} */

/*! @name PORTC15 (number 87), J1[5]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_Vibration_Check_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define BOARD_Vibration_Check_GPIO_PIN_MASK (1U << 15U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_Vibration_Check_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_Vibration_Check_PIN 15U                   /*!<@brief PORT pin number */
#define BOARD_Vibration_Check_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

/*! @name PORTE4 (number 5), SW3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_SW3_GPIO GPIOE               /*!<@brief GPIO peripheral base pointer */
#define BOARD_SW3_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_SW3_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_SW3_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_SW3_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                           /* @} */

/*! @name PORTA4 (number 38), SW2/NMI_b
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_SW2_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_SW2_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_SW2_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_SW2_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_SW2_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitBUTTONsPins(void);

#define PORT_DFER_DFE_1_MASK 0x02u /*!<@brief Digital Filter Enable Mask for item 1. */
#define PORT_DFER_DFE_7_MASK 0x80u /*!<@brief Digital Filter Enable Mask for item 7. */

/*! @name PORTE25 (number 32), D4[3]/LEDRGB_BLUE
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LED_BLUE_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED_BLUE_GPIO_PIN_MASK (1U << 25U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_LED_BLUE_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_LED_BLUE_PIN 25U                   /*!<@brief PORT pin number */
#define BOARD_LED_BLUE_PIN_MASK (1U << 25U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PORTD1 (number 94), D4[1]/LEDRGB_RED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LED_RED_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED_RED_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_LED_RED_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_LED_RED_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_LED_RED_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name PORTD7 (number 100), D4[4]/LEDRGB_GREEN
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LED_GREEN_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED_GREEN_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_LED_GREEN_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_LED_GREEN_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_LED_GREEN_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLEDsPins(void);

#define SOPT5_UART0TXSRC_UART_TX 0x00u /*!<@brief UART 0 transmit data source select: UART0_TX pin */

/*! @name PORTB16 (number 62), U7[4]/UART0_RX_TGTMCU
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_DEBUG_UART_RX_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_DEBUG_UART_RX_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_DEBUG_UART_RX_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORTB17 (number 63), U10[1]/UART0_TX_TGTMCU
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_DEBUG_UART_TX_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_DEBUG_UART_TX_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_DEBUG_UART_TX_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDEBUG_UARTPins(void);

/*! @name ADC1_DP1 (number 16), RT1/THER_A
  @{ */
/* @} */

/*! @name ADC1_DM1 (number 17), RT1/THER_B
  @{ */
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitTHERPins(void);

#define PORT_DFER_DFE_0_MASK 0x01u /*!<@brief Digital Filter Enable Mask for item 0. */
#define PORT_DFER_DFE_2_MASK 0x04u /*!<@brief Digital Filter Enable Mask for item 2. */
#define PORT_DFER_DFE_3_MASK 0x08u /*!<@brief Digital Filter Enable Mask for item 3. */

/*! @name PORTD2 (number 95), U8[4]/I2C0_SCL
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_ACCEL_SCL_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_ACCEL_SCL_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_ACCEL_SCL_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PORTD3 (number 96), U8[6]/I2C0_SDA
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_ACCEL_SDA_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_ACCEL_SDA_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_ACCEL_SDA_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PORTC18 (number 92), U8[9]/Sensor_INT2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_ACCEL_INT2_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define BOARD_ACCEL_INT2_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_ACCEL_INT2_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define BOARD_ACCEL_INT2_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_ACCEL_INT2_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PORTD0 (number 93), U8[11]/INT1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_ACCEL_INT1_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_ACCEL_INT1_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_ACCEL_INT1_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_ACCEL_INT1_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_ACCEL_INT1_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                  /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitACCELPins(void);

/*! @name PORTA18 (number 50), X501[1]/EXTAL0
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_EXTAL0_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_EXTAL0_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_EXTAL0_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name PORTA19 (number 51), X501[3]/XTAL0
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_XTAL0_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_XTAL0_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_XTAL0_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                              /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitOSCPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
